Repository DataBiosphere/data-store, pull requests merged in 2020-02, with the labels that each got.

#63 DSS Infra: add platform to CI/CD
  iam/policy-templates/ci-cd.json
  scripts/authorize_aws_deploy.sh
Labels: bug, dss_ops

#82 DSS Infra: add auth for terraform buckets
  iam/policy-templates/ci-cd.json
  scripts/authorize_aws_deploy.sh
Labels: dss_ops

#87 DSS Tests: Smoketest tool
  tests/infra/base_smoketest.py
Labels: bug

#89 DSS Infra: Secrets Check
  dss/operations/secrets.py
Labels: bug, dss_ops

#97 Add stage to API gateway deploy name
  chalice/app.py
  chalice/build_deploy_config.sh
Labels: added_to_sprint

#110 DSS Infra: Env updates
  environment
Labels: added_to_sprint, bug

#121 DSS Infra: Secrets Check
  environment
  scripts/check_deployment_secrets.py
Labels: bug
